[package]
name = "caescript"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "caescript"
path = "src/bin/main.rs"
required-features = ["build-binary"]

[dependencies]
byteorder = { version = "1.5.0", optional = true }
anyhow = { version = "1.0.75", optional = true }
strum = { version = "0.25", features = ["derive"] }
rustyline = { git="https://github.com/caelansar/rustyline.git", branch = "prompt4", optional = true }
tree-sitter-caescript = { path = "./tree-sitter-caescript", optional = true }
tree-sitter = { version = "0.24.4", optional = true }
tree-sitter-highlight = { version = "0.24.4", optional = true }

[build-dependencies]
chrono = "0.4.31"

[features]
default = ["vm", "build-binary"]
trace = []
vm = ["byteorder", "anyhow"]
build-binary = ["rustyline", "tree-sitter-caescript", "tree-sitter", "tree-sitter-highlight"]
fuzzy-completion = ["rustyline/with-fuzzy"]
